# Pipeline to deploy opsman to AWS using Pivotal's Platform Automation

# Download the Platform Automation image from Pivnet and push the image to your Gitlab repository 
image: registry.gitlab.com/miclip/acme-gitlab-aws-pas-dojo/platform-automation:2.1.1-beta

stages:
  - setup
  - configure-opsman
  - configure-pas
  

create-infrastructure:
  stage: setup
  image: pcfnorm/rootfs:1.0.28
  variables:
    S3_BUCKET_TERRAFORM: miclip-terraform
    S3_ENDPOINT: http://s3.amazonaws.com
    S3_REGION: us-east-2
    VARS_FILE: vars/mlsb/terraform.tfvars
    AWS_ACCESS_KEY_ID: $aws_access_key_id
    AWS_SECRET_ACCESS_KEY: $aws_secret_access_key
    TF_VAR_access_key: $aws_access_key_id
    TF_VAR_secret_key: $aws_secret_access_key
    TF_VAR_ssl_cert: $ssl_cert
    TF_VAR_ssl_private_key: $ssl_private_key
  script:
    - terraform init -backend-config="bucket=${S3_BUCKET_TERRAFORM}" -backend-config="key=mlsb/terraform.tfstate" -backend-config="region=${S3_REGION}" terraforming-pas
    - terraform plan -out=pcf.tfplan -var-file=${VARS_FILE} terraforming-pas
    - terraform apply pcf.tfplan

destroy-infrastructure:
  stage: setup
  image: pcfnorm/rootfs:1.0.28
  when: manual
  variables:
    S3_BUCKET_TERRAFORM: miclip-terraform
    S3_ENDPOINT: http://s3.amazonaws.com
    S3_REGION: us-east-2
    VARS_FILE: vars/mlsb/terraform.tfvars
    AWS_ACCESS_KEY_ID: $aws_access_key_id
    AWS_SECRET_ACCESS_KEY: $aws_secret_access_key
    TF_VAR_access_key: $aws_access_key_id
    TF_VAR_secret_key: $aws_secret_access_key
    TF_VAR_ssl_cert: $ssl_cert
    TF_VAR_ssl_private_key: $ssl_private_key
  script:
    - terraform init -backend-config="bucket=${S3_BUCKET_TERRAFORM}" -backend-config="key=mlsb/terraform.tfstate" -backend-config="region=${S3_REGION}" terraforming-pas
    - terraform destroy -input=false -auto-approve -var-file=${VARS_FILE} terraforming-pas
     
fetch-healthwatch:
  stage: setup
  when: manual
  variables:
    S3_BUCKET_TERRAFORM: miclip-terraform
    S3_ENDPOINT: http://s3.amazonaws.com
    S3_REGION: us-east-2
    AWS_ACCESS_KEY_ID: $aws_access_key_id
    AWS_SECRET_ACCESS_KEY: $aws_secret_access_key
    CONFIG_FILE: download-product-configs/healthwatch.yml
    VARS_FILES: ""
    FILES_GLOB: config/download-product-configs/healthwatch.yml
    VAR_PREFIX: DLP
    DLP_pivnet_token: $pivnet_token
    PRODUCT_NAME: healthwatch
  script: 
   - tasks/gitlab-interpolate.sh
   - tasks/download-product.sh
   - upload-product-s3.sh

fetch-pas:
  stage: setup
  when: manual
  variables:
    S3_BUCKET_TERRAFORM: miclip-terraform
    S3_ENDPOINT: http://s3.amazonaws.com
    S3_REGION: us-east-2
    AWS_ACCESS_KEY_ID: $aws_access_key_id
    AWS_SECRET_ACCESS_KEY: $aws_secret_access_key
    CONFIG_FILE: download-product-configs/pas.yml
    VARS_FILES: ""
    FILES_GLOB: config/download-product-configs/pas.yml
    VAR_PREFIX: DLP
    DLP_pivnet_token: $pivnet_token
    PRODUCT_NAME: pas
  script: 
   - tasks/gitlab-interpolate.sh
   - tasks/download-product.sh
   - upload-product-s3.sh


configure-opsman:
  stage: configure-opsman
  variables:
    VARS_FILES: vars/mlsb/director.yml
    OPS_FILES: ""
    FILES_GLOB: "vars/mlsb/*.yml env/mlsb/env.yml"
    ENV_FILE: mlsb/env.yml
    AUTH_CONFIG_FILE: vars/mlsb/auth.yml
    VAR_PREFIX: OPSMAN
    DIRECTOR_CONFIG_FILE: mlsb/director.yml
    OPSMAN_opsman_user_username: $opsman_user_username
    OPSMAN_opsman_user_password: $opsman_user_password
    OPSMAN_ops_manager_decryption_passphrase: $ops_manager_decryption_passphrase
    OPSMAN_opsman_keypair: $opsman_keypair
    OPSMAN_vms_security_group: $vms_security_group
    OPSMAN_trusted_certs: $trusted_certs
    OPSMAN_opsman_ssh_private_key: $opsman_ssh_private_key
  script:
   - tasks/gitlab-interpolate.sh
   - tasks/configure-authentication.sh
   - tasks/configure-director.sh
   - tasks/apply-director-changes.sh

configure-pas:
  stage: configure-pas
  variables:
    S3_BUCKET_TERRAFORM: miclip-terraform
    S3_ENDPOINT: http://s3.amazonaws.com
    S3_REGION: us-east-2
    AWS_ACCESS_KEY_ID: $aws_access_key_id
    AWS_SECRET_ACCESS_KEY: $aws_secret_access_key
    FILES_GLOB: "env/mlsb/env.yml"
    ENV_FILE: mlsb/env.yml
    PRODUCT_FILES: pas/downloaded-product
    CONFIG_FILE: ""
  script:
    - aws s3 --endpoint-url $S3_ENDPOINT --region $S3_REGION cp "s3://${S3_BUCKET_TERRAFORM}/artifacts/pas" pas --recursive
    - tasks/gitlab-interpolate.sh
    - tasks/upload-product.sh



