# Pipeline to deploy opsman to AWS using Pivotal's Platform Automation

# Download the Platform Automation image from Pivnet and push the image to your Gitlab repository 
image: registry.gitlab.com/miclip/acme-gitlab-aws-pas-dojo/platform-automation:2.1.1-beta

stages:
  - terraform
  - configure
  - fetch

create-infrastructure:
  stage: terraform
  image: pcfnorm/rootfs:1.0.28
  variables:
    S3_BUCKET_TERRAFORM: miclip-terraform
    S3_ENDPOINT: http://s3.amazonaws.com
    S3_REGION: us-east-2
    VARS_FILE: vars/mlsb/terraform.tfvars
    AWS_ACCESS_KEY_ID: $aws_access_key_id
    AWS_SECRET_ACCESS_KEY: $aws_secret_access_key
    TF_VAR_access_key: $aws_access_key_id
    TF_VAR_secret_key: $aws_secret_access_key
    TF_VAR_ssl_cert: $ssl_cert
    TF_VAR_ssl_private_key: $ssl_private_key
  script:
    - terraform init -backend-config="bucket=${S3_BUCKET_TERRAFORM}" -backend-config="key=mlsb/terraform.tfstate" -backend-config="region=${S3_REGION}" terraforming-pas
    - terraform plan -out=pcf.tfplan -var-file=${VARS_FILE} terraforming-pas
    - terraform apply pcf.tfplan

destroy-infrastructure:
  stage: terraform
  image: pcfnorm/rootfs:1.0.28
  when: manual
  variables:
    S3_BUCKET_TERRAFORM: miclip-terraform
    S3_ENDPOINT: http://s3.amazonaws.com
    S3_REGION: us-east-2
    VARS_FILE: vars/mlsb/terraform.tfvars
    AWS_ACCESS_KEY_ID: $aws_access_key_id
    AWS_SECRET_ACCESS_KEY: $aws_secret_access_key
    TF_VAR_access_key: $aws_access_key_id
    TF_VAR_secret_key: $aws_secret_access_key
    TF_VAR_ssl_cert: $ssl_cert
    TF_VAR_ssl_private_key: $ssl_private_key
  script:
    - terraform init -backend-config="bucket=${S3_BUCKET_TERRAFORM}" -backend-config="key=mlsb/terraform.tfstate" -backend-config="region=${S3_REGION}" terraforming-pas
    - terraform destroy -input=false -auto-approve -var-file=${VARS_FILE} terraforming-pas
     

fetch_healthwatch:
  stage: fetch
  artifacts:
    paths:    
      - downloaded-files/*.*
      - downloaded-stemcells/*.*
  variables:
    CONFIG_FILE: download-product-configs/healthwatch.yml
    VARS_FILES: ""
    FILES_GLOB: config/download-product-configs/healthwatch.yml
    VAR_PREFIX: DLP
    DLP_pivnet_token: $pivnet_token
  script: 
   - tasks/gitlab-interpolate.sh
   - tasks/download-product.sh


configure-authentication:
  stage: configure
  variables:
    VARS_FILES: ""
    FILES_GLOB: env/mlsb/env.yml
    ENV_FILE: mlsb/env.yml
    AUTH_CONFIG_FILE: mlsb/auth.yml
  script:
   - tasks/gitlab-interpolate.sh
   - tasks/configure-authentication.sh


