# Pipeline to deploy opsman to AWS using Pivotal's Platform Automation

# Download the Platform Automation image from Pivnet and push the image to your Gitlab repository 
image: registry.gitlab.com/miclip/acme-gitlab-aws-pas-dojo/platform-automation:2.1.1-beta

before_script:
  - echo "Before script section"
  - echo $pivnet_token
   
after_script:
  - echo "After script section"



stages:
  - fetch
  - deploy

# test1:
#  stage: test
#  script: tasks/test.sh
     
fetch_opsman:
  stage: fetch
  variables:
    CONFIG_FILE: download-product-configs/opsman.yml
    VARS_FILES: ""
    FILES_GLOB: config/download-product-configs/opsman.yml
    VAR_PREFIX: DLP
    DLP_pivnet_token: $pivnet_token
  script: 
   - tasks/gitlab-interpolate.sh
   - tasks/download-product.sh

fetch_healthwatch:
  stage: fetch
  variables:
    CONFIG_FILE: download-product-configs/healthwatch.yml
    VARS_FILES: ""
    FILES_GLOB: config/download-product-configs/healthwatch.yml
    VAR_PREFIX: DLP
    DLP_pivnet_token: $pivnet_token
  script: 
   - tasks/gitlab-interpolate.sh
   - tasks/download-product.sh


deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
