# Pipeline to deploy opsman to AWS using Pivotal's Platform Automation

# Download the Platform Automation image from Pivnet and push the image to your Gitlab repository 
image: registry.gitlab.com/miclip/acme-gitlab-aws-pas-dojo/platform-automation:2.1.1-beta

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"
   
after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"
   
test1:
  stage: test
  script: tasks/test.sh
     
fetch_opsman:
  stage: build
  variables:
    CONFIG_FILE: download-product-config/opsman.yml
    VARS_FILES: ""
  script: tasks/download-product.sh


deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
